version: 2.1

jobs:

  build-and-push:
    docker:
      - image: cimg/node:18.0

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 320042238069.dkr.ecr.ap-south-1.amazonaws.com
      - run:
          name: Build & Push Image
          command: |
            docker build -t shoopingcart .

            docker tag shoopingcart:latest 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest

            docker push 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest


  terraform-infra:
    docker:
      - image: hashicorp/terraform:1.6

    steps:
      - checkout

      - run:
          name: Terraform Apply (safe)
          command: |
            cd terraform
            terraform init -input=false

            # SAFE APPROACH: always apply but no re-create issues
            terraform apply -auto-approve


  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: Install tools
          command: |
            sudo apt update
            sudo apt install -y openssh-client curl unzip

            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Deploy via SSH (FIXED)
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP "
              set -e

              aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 320042238069.dkr.ecr.ap-south-1.amazonaws.com
              cd /home/ec2-user/app

              docker compose pull
              docker compose down || true
              docker compose up -d --remove-orphans
            "

workflows:
  build-infra-deploy:
    jobs:
      - build-and-push
      - terraform-infra:
          requires:
            - build-and-push
      - deploy:
          requires:
            - terraform-infra