version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/node:18.0

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPOSITORY .

      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install -y awscli

      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 320042238069.dkr.ecr.ap-south-1.a

      - run:
          name: Tag Image
          command: |
            docker tag shoopingcart:latest 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest

      - run:
          name: Push Image
          command: |
            docker push 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest


  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
            cd $PROJECT_DIR &&
            docker compose down &&
            docker pull 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest
            docker tag 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest shopping-cart &&
            docker compose up -d
            '

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push