version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/node:18.0

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install -y awscli

      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region ap-south-1 \
            | docker login --username AWS --password-stdin 320042238069.dkr.ecr.ap-south-1.amazonaws.com

      - run:
          name: Build Docker Image
          command: |
            docker build -t shoppingcart .

      - run:
          name: Tag Image
          command: |
            docker tag shoppingcart:latest 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest

      - run:
          name: Push Image
          command: |
            docker push 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest


  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - ${SSH_KEY_FINGERPRINT}

      - run:
          name: Add EC2 to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@EC2_HOST "
              cd /home/ec2-user/E-commerce-website &&
              docker compose down &&
              docker pull 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest &&
              docker tag 320042238069.dkr.ecr.ap-south-1.amazonaws.com/shoopingcart:latest shopping-cart &&
              docker compose up -d
            "

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push